

<div class="chat-list" id="0" data-resource="0" data-name="name">

  <a class="all-users" id="0" data-resource="0" data-name="name" style="color:#333"><span class='iconb' data-icon=&#xe1e1;></span> All</a>

    <?php foreach($listUsers as $user){ ?>

       <a  id="<?php echo $user['id_user'] ?>" class="<?php echo $user['id_resource'] ?>"   data-name="<?php echo $user['name'] ?>"  data-resource="<?php echo $user['id_resource'] ?>" >
           <span class='iconb' data-icon=&#xe1e0;></span> <?php echo str_replace(' ','',$user['name']) ?>
       </a>

    <? } ?>

</div>

<script>

    WChat();

    function WChat(){

        var chatList  = $('.chat-list');

        chatList.find(" a." + $('.chat-pos').attr('data-resource')).addClass('im');

        chatList.find('a').click(function() {

            chatList.find('a').removeClass('active');
            $(this).addClass('active');

            log('click');

            var id       =  $(this).attr('id');
            var resource =  $(this).attr('data-resource');
            var name     =  $(this).attr('data-name');

            chatList.attr('id',id);
            chatList.attr('data-resource',resource);
            chatList.attr('data-name',name);

            return  resource;
        });

        return  chatList.attr('data-resource');
    }

</script>