

<?php foreach($messages as $message){ ?>


    <?php if($id_user == $message['id_user']){ ?>

        <?php  echo strftime("%k:%M:%S", strtotime($message['date']));  ?>
        <strong>
            <?php  echo $message['name'] ?>
        </strong>:
        <?php echo $message['message'] ?>
        <br>

    <? }elseif($id_user  == $message['id_user_parent'] || $message['id_user_parent'] == 0 ){ ?>

        <span class="userC">
            <?php  echo strftime("%k:%M:%S", strtotime($message['date']));  ?>
            <strong>
                <?php  echo $message['name'] ?>
            </strong>:
            <?php echo $message['message'] ?>
        </span>
        <br>

    <? } ?>

<? } ?>

